/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw481;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void nullArray(){
        int[] array=null;
        assertThrows(
            IllegalArgumentException.class,
            () -> {App.modifyArray(array,1,"1",1); }
        );
    }
    
    @Test void illegalType(){
        int[] array=new int[]{1,2,3};
        assertThrows(
            IllegalArgumentException.class,
            () -> {App.modifyArray(array,1,"3",1); }
        );
    }

    @Test void negativeIndex(){
        int[] array=new int[]{1,2,3};
        assertThrows(
            IllegalArgumentException.class,
            () -> {App.modifyArray(array,1,"3",-1); }
        );
    }

    @Test void indexIsGreaterThenLength(){
        int[] array=new int[]{1,2,3};
        assertThrows(
            IllegalArgumentException.class,
            () -> {App.modifyArray(array,1,"3",6); }
        );
    }

    @Test void addSuccesfully(){
        int[] array=new int[]{1,2,4};
        assertEquals( 1 , App.modifyArray(array,3,"1",2)[0] );
        assertEquals( 2 , App.modifyArray(array,3,"1",2)[1] );
        assertEquals( 3 , App.modifyArray(array,3,"1",2)[2] );
        assertEquals( 4 , App.modifyArray(array,3,"1",2)[3] );
    }

    @Test void deleteSuccesfully(){
        int[] array=new int[]{1,2,3};
        assertEquals( 1 , App.modifyArray(array,2,"2",1)[0] );
        assertEquals( 3 , App.modifyArray(array,2,"2",1)[1] );
    }
}
