/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw481;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    
    public static int[] modifyArray(int[] array,int e,String type,Integer index){
       
        if(array==null || index<0 || index>(array.length+1) ){
            throw new IllegalArgumentException();
       }

       if(type.equals("1")){ //eleman ekleme
               
               int[] newArr=new int[array.length+1];
            int j=0;
            for(int i=0;i<array.length+1;i++){
                
                if(index.compareTo(i)==0){
                    newArr[index.intValue()]=e;
                }
                else{
                    newArr[i]=array[j];
                    j++;
                }
            }
            return newArr;
       }
       else if(type.equals("2")){ //eleman cikarma
           
           int[] newArr=new int[array.length-1];
           int j=0;
           for(int i=0;i<array.length;i++) {
               
               if(index.compareTo(i)!=0) {
                   newArr[j]=array[i];
                   j++;
               }
           }
           
           return newArr;
       }

       else{
            throw new IllegalArgumentException();
       }


    }
}
